### ISSUE TITLE
Publish #1 to NPM

### ISSUE THREAD

**Issue by madmod** [swissmanu/harmonyhubjs-discover#2]
Could you please publish #1 to NPM? Thanks!

**Comment by maddox** [comment]
:+1: to this. #1 fixes a serious bug, and we have to tie the npm package to the git URL instead of pointing at NPM because of it.

**Comment by swissmanu** [comment]
finally published version `1.0.1` with the bugfix by @madmod.
thx for contribution & waiting.

https://www.npmjs.com/package/harmonyhubjs-discover

**Comment by madmod** [comment]
Thanks for the project! :D
